spring.application.name=demo
# ====== JSP ======
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ====== MYSQL ======
spring.datasource.url=jdbc:mysql://localhost:3307/demo?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ====== JPA ======
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ====== LOGGING ==========
# Log level t?ng
logging.level.root=INFO

# Log riêng cho project
logging.level.org.example.demo=INFO

# Ghi log ra file
logging.file.name=logs/app.log

# Format log (d? ??c)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n